stages:
  - clean

lint:
    stage: clean
    image: node:latest
    script:
      - npm install -g eslint \
          eslint-plugin-react \
          eslint-config-prettier \
            eslint-plugin-prettier \
            eslint-plugin-react-hooks \ 
            eslint-plugin-simple-import-sort \
            @typescript-eslint/eslint-plugin \
            @typescript-eslint/parser \
            prettier
      - eslint --version
      - eslint ./ --ext .js,.jsx,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore