stages:
  - clean
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

lint:
  stage: clean
  image: node:latest
  script:
    - npm install
    - npm run lint:check

install:
  image: cypress/base:10
  stage: build

  script:
    - if [ -f package-lock.json ]; then npm ci; else npm install; fi
    - npm ci
    - $(npm bin)/cypress cache path
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify

cypress-component:
  image: cypress/base:10
  stage: test
  script:
    - $(npm bin)/cypress run --config video=false --component
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/screenshots
    reports:
      junit:
        - results/TEST-*.xml
